### ISSUE TITLE
WARNING -- EARLY TESTING CHANNEL -- KNOWN BROKEN (DEVELOPERS ONLY)

### ISSUE THREAD

**Issue by phillxnet** [rockstor/rockstor-core#2362]
Our Web-UI parses the rockstor package update changelog and displays those entries it understands, ignoring others.

This issue enables us to display, within the Web-UI, the above capitalised warning. And via the associated issue link, this text.

We are embarking on a massive set of code changes that will initially leave the **testing rpms broken** and so of **little use to non-developers**. 

We would like to inform non-developer testers of the following status:

## Known issues:
- [x] More recent oathlib version is Python 3 only (sorted by pinning in additional commit to #2365 ).
- [x] On submitting initial setup / admin user screen we have a variable type error, See Issue #2366 .
- [x] On reboot there is a catastrophic database migration failure that has yet to be resolved (#2376).
- [ ] 14 of 208 unit tests indicate multiple failures/errors likely associated with our in-progress Django update (see #2254). Issue #2371 
- [x] Mostly dysfunctional Dashboard (issue to follow). See /var/log/nginx/error.log for socket.io failed connections. Issue #2368
- [x] Inaccessible Replication pages; Send, Receive, likely pending Django url changes #2370.
- [x] Inaccessible Services page. Issue: #2370 
- [x] Inaccessible Task page, thanks @Hooverdan96. Issue: #2370
- [x] All System pages inaccessible intermittently (Services always fails). Post visiting Rock-ons then network some are then available!! Mostly related to #2368.
- [x] We don't appear to be starting all our apps: See:  /opt/rockstor-dev/var/log/supervisord_data-collector_stderr.log #2368 
- [x] The associated update of djangorestframework in #2365 has resulting in a generic requirement to move from request.DATA to request.data. See Issue #2379 
- [x] Django management commands are failing to run. Issue: #2377

More details to follow as we establish the new testing branch/phase and it's associated build system changes.

**Comment by phillxnet** [comment]
Closing this meta-issue now as much water has passed under the theoretical bridge. We now have entirely working testing and have more than restored our past test coverage - sorting the last outstanding tick in this issue.

The Modernisation of source code issue linked here has received some attention also give we are not Poetry based. But that issue will likely be closed as unattainable given there is always ongoing progress in all our many upstreams.

Closing as fixed given we are now longer in early testing, but in Release Candidate phase.
