### ISSUE TITLE
Milestones for default & optional environment & volume-mapping fields

### ISSUE THREAD

**Issue by kanecko** [rockstor/rockstor-core#2937]
I thought of making a parent issue so we can track the progress being made.

- [ ] Add support for default values in required environment fields. #2012
- [ ] Add support for default values in required **volume-mapping** fields. 
- [ ] Add support for **optional** values in **environment** fields.  #2094
- [ ] Add support for optional values in **volume-mapping** fields. #2280
- [ ] Update the following Rockons with default and optional fields:
   - [ ] pi-hole
   - [ ] jellyfin
   - [ ] netalertx
   - [ ] omada-controller
   - [ ] nginx-proxy-manager
   - [ ] radarr
   - [ ] sonarr
   - [ ] transmission
   - [ ] **(please suggest others as well!)**
- [ ] Add new Rockon "Unpackerr"

**Comment by phillxnet** [comment]
@FroggyFlox & @Hooverdan96 Should we make this into a Milestone proper? I.e. we have now it seems reached some-what of a critical mass on our Rock-ons v1 lets say: arbitrarily. Maybe we have sufficient interest, re @kanecko renewed presence, to establish a Rock-ons V2 milestone. To be addressed as interest/resources allow, in parallel with our front end updates. Partial conflict but that is unavoidable with the large changes we have already made in the past: and are still planning for re UI dependencies re-vamp.

Super important in all these Rock-ons changes is to not break at least our last Stable, currently 4.6.1-0, and ideally last but one 4.1.0-0. But with our next Stable just around the corner we might only really have to concern ourselves re backward compatibility to 4.6.1-0 in the very near future; as we will then have a 5.1.0-0. And thus far changes such as convenience defaults honours this (at least I think/hope it does).

We need not list all affected Rock-ons as that is redundant and dynamic: we need only collect issues that detail planned Rock-on subsystem improvements. Especially as we have to honour all existing installs (last one or two stables). Alternatively we just use issue labels: but they are less obvious progress wise. And if we have a renewed interest in upping the Rock-on sub-system it would be good to establish this up-front via an Issue Milestone.

@kanecko Great to have renewed interest in our Rock-ons subsystem. However we are unlikely to be able to cram any of these deeper (model change) improvements into the next Stable (current testing before Stable spin-off) but that does give us way more leeway to make bolder changes in the testing channel there-after (soon). So all good: especially as we are all after a much shorter testing phase the next go around.

**Comment by kanecko** [comment]
I would like to finish _Add support for default values in required environment fields_ at some point since the Christmas vacations are nearing. IIRC, only tests were missing.

I am just wondering, if there are any hesitations to work on this? Do you have any special revamp plans for Rock-ons, or can I continue with my work as-is?

**Comment by phillxnet** [comment]
@kanecko Re:

> I would like to finish _Add support for default values in required environment fields_

The following https://github.com/rockstor/rockstor-core/pull/2938 was closed without being merged.

> I am just wondering, if there are any hesitations to work on this?

If you are game then great, but as per prior comments here we must take care to not break existing Rock-on functionality/compatibility.

> Do you have any special revamp plans for Rock-ons

We plan to re-vamp the entire front-end. But that is a mid-term plan and a non-trivial one at that!

> can I continue with my work as-is?

As always pull requests as proofs of concept are best here I think. After having defined the problem/improvement that you intent to addess in as narrowly defined issue as possible.

@magicalyak's https://github.com/rockstor/rockstor-core/issues/2012 does this but we also need to consider our ongoing work on the new Rock-on validator https://github.com/rockstor/rockon-validator : and backward compatibility also of course.

Re Rock-ons - they are here to stay for sure. We now have loads of them and I at least do not intend to throw out all the work many folks have put into them. But yes, they are in need of improvements as per the issues related to them in their own repo and here in core. Plus also now in the rockon-validator repo.

@Hooverdan96 and/or @FroggyFlox  Could you chip-in on @kanecko questions here - I'm a little out-of-touch currently in this area.

**Comment by kanecko** [comment]
I see two paths: 
1. my current changes get merged, when they are good enough.
2. I scrap the current PoC and work on the mid-term, non-trivial re-vamp of the entire front-end instead.

Motivation-wise, I would prefer to work on things that have a higher change of getting merged than not. If the re-vamp will override my current PoC, I would prefer to work on the re-vamp instead (or anything else, really).

**Comment by magicalyak** [comment]
I think being open to a new revamp is a good direction, I've been trying to
contribute as best I can but the rockons could likely be ported if needed
also.

**Comment by phillxnet** [comment]
@kanecko Fully under. And this has been an factor for all the core contributors. But technologies always change and we would have no Web-UI if we didn't start out with at least one. However my

> We plan to re-vamp the entire front-end.

doesn't quite capture the plan here. We are after removing as much JS as is technologically possible: hence the mid (to long probably) term nature. And to achieve this we are in the process of updating all our back-end capabilities. Keep an eye on our existing milestones for how this is going.

The current hand-coded JS of all our front end is arcane - that is the 're-vamp' I'm referencing. But of course - we are to transition all that is to what will be. So yes: major JS contributions would be a wast of time. And we are, as yet, still settling on the technologies involved in the new front-end. But back-end first, then API / serialisation layer, then front end. And we are currently working on the back-end: but getting somewhere as we go.

Re: 

> (or anything else, really).

We have outstanding hundreds of issues -but prioritise via our existing milestones. The proposed Milestone in this issue does not exist. But we do want to improve our Rock-ons. But most of that improvement comes initially from the back-end. I.e. such things as:

- https://github.com/rockstor/rockstor-core/issues/3029

A feature you have hard-wired in one of your recent contributions. That sort of issue is relatively trivial to add and takes priority over many others given it provides a utility that is already required and more frequently considers in more recent docker images. @Hooverdan96 has also detailed of late many missing key features via issues. And my own Bareos Backeup Server work broght to light a few other short-falls - some were worked around and others needed inane doc entries for a system that is intended to be easy. But we are few and no front end can add what is not already in the back-end. At least not in a sane manner.

The front end re-write (likely looking similar once done) will most likely use as many native and modern Django facilities as we can cram in. With as little JS as we can possibly get away with: ergo our current and last Milestones as is/was. I.e. look to all the JS libraries we already carry via:

- https://github.com/rockstor/rockstor-jslibs

Ideally that repo should not exist, or should at least be pared down to an absolute minimum.

If the Rock-on subsystem is of most interest to you, look to the most recent issues there in core and see if any take your fancy. @Hooverdan96 has been most instrumental in steering recent Rock-on capability, both in core issues and via his maintainer-ship of the Rockons-registry. But @FroggyFlox is likely the most knowledgeable of the sub-system itself currently.

Hope that helps, at least with some context. And try not to be discouraged by any of this. We have made great progress in the last few years - but we have rather been buried in technical dept that we are just digging our way out of - and this has not been helped by major changes that visited many of the projects we have relied on. Ergo stepping carefully in our technology choices as we proceed.

**Comment by phillxnet** [comment]
@magicalyak Hello again. Re:

> but the rockons could likely be ported if needed also.

Yes, our rockon-validator: https://github.com/rockstor/rockon-validator is part of the plan to maintain them more effectively as it goes. It needs more work but should help with our ability to maintain their function - or help to move them all whole-sale over to an extended format for example.

**Comment by kanecko** [comment]
Thanks for the context! I just want to be useful and not forcefully go against the stream :)

> We have outstanding hundreds of issues -but prioritise via our existing milestones. 

> If the Rock-on subsystem is of most interest to you, look to the most recent issues there in core and see if any take your fancy. 

I will have a look around! Thanks for the direction.

Yeah, I suppose I didn't realize it till now that I strongly believe that the Rock-on subsystem is one of the key components of Rockstor. I even dreamed of Rockstor having the capability of automatically importing any dockerfiles and even docker-compose files. But enough dreaming for now... :)

**Comment by Hooverdan96** [comment]
> If the Rock-on subsystem is of most interest to you, look to the most recent issues there in core and see if any take your fancy. @Hooverdan96 has been most instrumental in steering recent Rock-on capability, both in core issues and via his maintainer-ship of the Rockons-registry. But @FroggyFlox is likely the most knowledgeable of the sub-system itself currently.

Completely agree on that one. For many of the details inside the underlying Rockon subsystem @FroggyFlox is the right expert.

@kanecko thanks for your interest in that area! Hope you will be able to realize your various ideas over time.
